pipeline {
    agent any

    stages {
        stage('Display Java Version') {
            steps {
                sh 'java --version'
            }
        }
        
        stage('Compile Java Program and create Jar file') {
            steps {
                sh '''
                    cd java-jdbc-app
                    javac -d . Product.java
                    javac -d . ProductDAO.java
                    javac -d . JdbcAppMain.java

                    jar cfm java-jdbc-app.jar manifest/MANIFEST.MF ./demos

                    docker build -t java-jdbc-app .

                    # List Docker images to verify
                    docker images

                    docker compose -f ./docker-compose.yml up --build
                    
                '''
            }

        }
    }
}