networks:
  host_network:
    external:true
services:
  mysql:
    image: mysql:oraclelinux9
    restart: always
    #build:
      #context: .
      #dockerfile: Dockerfile.mysql # The Dockerfile for MySQL
    container_name: mysql-container
    networks:
      - host_network
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jdbc_demos
      #MYSQL_ROOT_HOST: '%'  # Allow root to connect from any host
    ports:
      - "3307:3306"
    volumes:
      - ./java_springboot_app_data:/var/lib/mysql 
      #- ./data.sql:/docker-entrypoint-initdb.d/data.sql # Mount SQL file to the init directory
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10  # Increase retries to allow for longer startup
      start_period: 90s  # Give MySQL more time to initialize
      timeout: 300s
    
  app:
    image: java-springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-springboot-app-container
    networks:
      - host_network
    ports:
      - "9090:9090" # Host:Container
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      mysql:
        condition: service_healthy
    
    stdin_open: true      # Keep stdin open to accept input
    tty: true             # Enable TTY mode

volumes:
  java_springboot_app_data:  



