pipeline {
    agent any

    /*environment {
        MAVEN_HOME = tool 'Maven'  // Ensure Maven is installed in Jenkins
    }*/

    stages {

        stage('Display Maven version') {
            steps {
                // Run Maven build
                sh "mvn --version"
            }
        }
        stage('Build') {
            steps {
                sh '''
                    cd java-springboot-app
                    mvn clean package
                '''
                
            }
        }

        

        stage('Run') {    
            steps {
                script {

                    /*sh '''
                        cd java-springboot-app
                        docker compose -f ./docker-compose.yaml down
                    '''
                    */

                    sh '''
                        cd java-springboot-app
                        docker compose -f ./docker-compose.yaml up
                    '''

                    // Wait for MySQL container to be ready
                    /*sh '''
                        while ! docker exec mysql-container mysqladmin ping -h"localhost" --silent; do
                            echo "Waiting for MySQL to be ready..."
                            sleep 5
                        done
                    '''

                    // Restart the Spring Boot application container
                    sh '''
                        docker compose -f ./docker-compose.yaml restart app
                    '''
                    */
                    
                }
            }
        }

        
    }
}