pipeline {
    agent any

    /*environment {
        MAVEN_HOME = tool 'Maven'  // Ensure Maven is installed in Jenkins
    }*/

    stages {

        stage('Display Maven version') {
            steps {
                // Run Maven build
                sh "mvn --version"
            }
        }

        stage('Docker compose down') {
            steps {
                 sh '''
                        cd java-springboot-app
                        docker compose -f ./docker-compose.yaml down
                    '''
            }
        }

        stage('Prepare Environment') {
            steps {
                // Ensure wait-for-it.sh is executable
                sh '''
                    cd java-springboot-app
                    chmod +x $WORKSPACE/scripts/wait-for-it.sh
                '''
               
            }
        }
        stage('Build') {
            steps {
                sh '''
                    cd java-springboot-app
                    docker compose up -d my-mysql
                    
                    docker exec mysql-container mysqladmin ping -h my-mysql -u root -p123456
                    

                    # Wait until MySQL is ready
                    $WORKSPACE/scripts/wait-for-it.sh my-mysql:3306 -t 200

                    mvn clean package -DskipTests
                '''
                
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd java-springboot-app
                    mvn test
                '''
            }
        }


        

        stage('Run') {    
            steps {
                script {

                    /*sh '''
                        cd java-springboot-app
                        docker compose -f ./docker-compose.yaml down
                    '''
                    */

                    sh '''
                        cd java-springboot-app
                        
                        docker compose -f ./docker-compose.yaml up --build -d
                        
                    '''

                    // Wait for MySQL container to be ready
                    /*sh '''
                        while ! docker exec mysql-container mysqladmin ping -h"localhost" --silent; do
                            echo "Waiting for MySQL to be ready..."
                            sleep 5
                        done
                    '''

                    // Restart the Spring Boot application container
                    sh '''
                        docker compose -f ./docker-compose.yaml restart app
                    '''
                    */
                    
                }
            }
        }

        
    }
}