pipeline {
    agent any

    stages {
        stage('Display Java Version') {
            steps {
                sh 'java --version'
            }
        }
        
        stage('Compile Java Program and create Jar file') {
            steps {
                sh '''
                    cd java-hello-user
                    javac HelloUser.java
                    jar cfe hello-user.jar HelloUser HelloUser.class

                    docker build -t hello-user .

                    # List Docker images to verify
                    docker images

                    docker run -it --name hello-user-container hello-user /bin/bash
                    
                    
                '''
            }

        }

        /*stage('build the image and start the docker container') {
            steps {
                sh '''
                    
                    
                '''
            }
        }*/
    }
}