pipeline {
    agent any

    stages {
        stage('Display Java Version') {
            steps {
                sh 'java --version'
            }
        }
        stage('Compile Java Program') {
            steps {
                sh 'javac java-hello-world/HelloWorld.java'
            }
        }
        stage('Run Java Program') {
            steps {
                sh 'java java-hello-world/HelloWorld'
            }
        }
    }
}