pipeline {
    agent any

    /*environment {
        MAVEN_HOME = tool 'Maven'  // Ensure Maven is installed in Jenkins
    }*/

    stages {

        stage('Display Maven version') {
            steps {
                // Run Maven build
                sh "mvn --version"
            }
        }
        stage('Build') {
            steps {
                // Run Maven build
                sh "mvn clean package"
            }
        }

        /*stage('Run') {
            steps {
                script {
                    
                    sh "java -jar target/java-hibernate-app-0.0.1-SNAPSHOT-jar-with-dependencies.jar"
                }
            }
        }*/

        
    }
}